### ISSUE TITLE
Socket error: unexpected server response (200)

### ISSUE THREAD

**Issue by williewh** [PaulAvery/kodi-ws#15]
Hi, I am getting this error in terminal from my code. I also tried it with mute.js and am getting the same error. My node version is v0.12.15. I understand I'm not doing something correctly.

user@dev:~/test$ node mute.js
Error: Socket error: unexpected server response (200)
    at ClientRequest.response (/home/user/testcode/node_modules/kodi-ws/node_modules/ws/lib/WebSocket.js:674:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by PaulAvery** [comment]
Hmm, are you sure your kodi installation is running on the default port?
I cannot reproduce the error on my end.

The error does suggest however, that your kodi installation does not respond correctly. Do you have the websocket control enabled in your kodi installation?

**Comment by tszumowski** [comment]
I'm getting the same exact error as williewh above. Here is my exact console output, when executing from a clone today:
```
C:\Users\test\workspace\kodi-ws\examples>node mute.js
Error: Socket error: unexpected server response (200)
    at ClientRequest.response (C:\Users\test\workspace\kodi-ws\node_modules\ws\lib\WebSocket.js:719:15)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
```


My node version is v6.3.1. I am running Kodi v16.1 “Jarvis”. Is it compatible with that version? In addition, I went to http://127.0.0.1:9090 in my browser and am able to mute/unmute from the web browser.  

When I follow my kodi debug log, I don't see any external RPC requests coming through. I also attached two screenshots that show my webserver settings
![untitled](https://cloud.githubusercontent.com/assets/10282962/20645531/35744b8a-b42f-11e6-820b-7b4b10032bdf.png)
![untitled2](https://cloud.githubusercontent.com/assets/10282962/20645532/3575dca2-b42f-11e6-9d86-2760616d4bc9.png)

**Comment by UhhhWaitWhat** [comment]
Hi @tszumowski,
first off, thanks for the screenshots.

Kodi uses two ports, one for the webinterface (by default 8080) and one for the socket connections (by default 9090).
The port for the webinterface is configurable in the kodi settings while the socket is only configurable through the advanced settings file.
I guess because you set your webinterface to port 9090 the socket server is not started.
Try to set the webserver port in your kodi settings to anything but 9090 but keep passing 9090 to this module.
I will put a note about this in the Readme because it definitely is not well documented.

**Comment by tszumowski** [comment]
@PaulAvery - Spot on! I changed the webinterface back to 8080 and didn't touch anything with the module, as you recommended. I didn't need to put anything into advancedsettings.xml either. It worked immediately. So it looks as if the webinterface's port takes priority in port settings over the socket server. Thank you!

I would recommend closing this issue since the OP had the same exact error message as me.

**Comment by UhhhWaitWhat** [comment]
That is great to hear :)
